#ifndef GUARD_CONSTANTS_EGG_MOVES_H
#define GUARD_CONSTANTS_EGG_MOVES_H

#define EGG_MOVES_SPECIES_OFFSET 20000
#define EGG_MOVES_TERMINATOR 0xFFFF

extern const u16 gEggMoves[];

#endif // GUARD_CONSTANTS_EGG_MOVES_H
