PalletTown_PlayersHouse_2F_Text_PlayedWithNES::
    .string "{PLAYER} played with the NES.\p"
    .string "…Okay!\n"
    .string "It's time to go!$"

PalletTown_PlayersHouse_2F_Text_PressLRForHelp::
    .string "It's a posted notice…\p"
    .string "If you're confused, ask for HELP!\n"
    .string "Press the L or R Button!$"

PalletTown_PlayersHouse_2F_Text_Give_Item::
    .string "Povo da SEEK aproveitem esse jogo\p"
    .string "modificado para voces!\n"
    .string "Aqui vai um pequeno presente meu.$"

PalletTown_PlayersHouse_2F_Text_Give_Item1::
    .string "Receba 20 RARY CANDY da zoeira ai.$"

