SilphCo_1F_Text_WelcomePresidentInBoardroom::
    .string "Welcome.\p"
    .string "The PRESIDENT is in the boardroom\n"
    .string "on 11F.$"

@ Tentative translation. Unknown origin
SilphCo_1F_Text_DestroyedWontBeFixedForWhile::
    .string "めちゃめちゃに　こわされてる\n"
    .string "とうぶん　なおりそうに　ない‥$"

SilphCo_1F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "1F$"

SilphCo_1F_Text_ExitGuardIntro::
    .string "Where do you think you're going?\p"
    .string "Nobody leaves SILPH CO. before the\n"
    .string "BOSS gives the order!$"

SilphCo_1F_Text_ExitGuardDefeat::
    .string "Impossible... You brought us down\n"
    .string "with your own two hands...$"

SilphCo_1F_Text_ExitGuardPostBattle::
    .string "Ugh... I'm not trained for this.\p"
    .string "The BOSS will hear about you, brat!\n"
    .string "I'm getting out of here!$"

SilphCo_1F_Text_ExitGuardTalk::
    .string "This exit is off limits.\p"
    .string "Turn back while you still can.$"

