SSAnne_Exterior_Text_City12Sign::
    .string "Truck driver leans against his rig.\p"
    .string "Headed to the island city?\n"
    .string "Want a ride?$"

SSAnne_Exterior_Text_City12Sign_Warp:
    .string "Hop in. We're leaving.$"

SSAnne_Exterior_Text_City12Sign_Declined:
    .string "Suit yourself.$"

SSAnne_Exterior_Text_ShipGoneSailor:
    .string "The S.S. ANNE has already\n"
    .string "set sail. You're too late.$"
