CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
    .string "Only skilled TRAINERS can collect\n"
    .string "POKéMON BADGES.\p"
    .string "I see you have at least one.\n"
    .string "Those BADGES have amazing secrets.\p"
    .string "Each of they increase in 5 levels\n"
    .string "the max obedience of your POKéMON\p"
    .string "Did you know, we have one BADGE for\n"
    .string "each POKéMON type?\p"
    .string "Do you want to learn more?$"

CeruleanCity_House1_Text_DescribeWhichBadge::
    .string "Now then…\p"
    .string "Which of the fifithen BADGES should\n"
    .string "I describe?$"

CeruleanCity_House1_Text_ComeVisitAnytime::
    .string "Come visit me anytime you wish.$"

CeruleanCity_House1_Text_AttackStatFlash::
    .string "It allow you use the move\n"
    .string "FLASH outside of battle.$"

CeruleanCity_House1_Text_ObeyLv30Cut::
    .string "It lets you use the move\n"
    .string "CUT outside of battle.$"

CeruleanCity_House1_Text_SpeedStatFly::
    .string "It allow you to use the move\n"
    .string "FLY outside of battle.$"

CeruleanCity_House1_Text_ObeyLv50Strength::
    .string "It lets you use the move\n"
    .string "STRENGTH outside of battle.$"

CeruleanCity_House1_Text_DefenseStatSurf::
    .string "It lets you use the move\n"
    .string "SURF outside of battle.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
    .string "It lets you use the move\n"
    .string "ROCK SMASH outside of battle.$"

CeruleanCity_House1_Text_SpStatsWaterfall::
    .string "It lets you to use the move\n"
    .string "WATERFALL outside of battle.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
    .string "The final BADGE! It is an evidence\n"
    .string "that you is master POKéMON TRAINER.$"

CeruleanCity_House1_Text_Stream::
    .string "It shows that you learned the cold\n"
    .string "secrets of the islands.$"

CeruleanCity_House1_Text_Valor::
    .string "It shows that you learned where to\n"
    .string "search for a fight.$"

CeruleanCity_House1_Text_Bug::
    .string "It shows that you learned all secrets\n"
    .string "off the forests.$"

CeruleanCity_House1_Text_Ghost::
    .string "It shows that you learned to be\n"
    .string "kind with all people.$"

CeruleanCity_House1_Text_Cupper::
    .string "It shows that you are ready to be\n"
    .string "a Nuzlocker.$"

CeruleanCity_House1_Text_Freedon::
    .string "It shows that you learned to\n"
    .string "pay attention to the details.$"

CeruleanCity_House1_Text_Heart::
    .string "It shows that you learned secret off\n"
    .string "the Dragonite's Island.$"
