Dark_city_MapScripts::
	.byte 0

Dark_City_GymKaz_Desc::
	lock
	msgbox Dark_City_GymKaz_Desc_Text_0
	closemessage
	releaseall
	end


Dark_City_GymYas_Desc::
	lock
	msgbox Dark_City_GymYas_Desc_Text_0
	closemessage
	releaseall
	end


Dark_City_Poke_center::
	lock
	msgbox Dark_City_Poke_center_Text_0
	closemessage
	releaseall
	end


Dark_City_Sale::
	lock
	msgbox Dark_City_Sale_Text_0
	closemessage
	releaseall
	end


Dark_City_lock_msg::
	lock
	msgbox Dark_City_lock_msg_Text_0
	closemessage
	releaseall
	end


Dark_City_abandoned_msg::
	lock
	msgbox Dark_City_abandoned_msg_Text_0
	closemessage
	releaseall
	end


Dark_City_GymKaz_Desc_Text_0:
	.string "Kaz Gym$"

Dark_City_GymYas_Desc_Text_0:
	.string "Yaz Gym$"

Dark_City_Poke_center_Text_0:
	.string "Closed.\p"
	.string "In case of a emergency, go to the\n"
	.string "Fushia center$"

Dark_City_Sale_Text_0:
	.string "For Sale$"

Dark_City_lock_msg_Text_0:
	.string "The door is locked.$"

Dark_City_abandoned_msg_Text_0:
	.string "It looks like this house is abandoned.$"
