CeladonCity_Hotel_Text_ThisHotelIsForPeople::
    .string "POKéMON?\n"
    .string "No, this is a hotel for people.\p"
    .string "We're full up, unfortunately.$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
    .string "I'm on vacation with my brother and\n"
    .string "boyfriend.\p"
    .string "CELADON is such a pretty city!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
    .string "Why?\n"
    .string "Why did she bring her brother?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
    .string "Yippee! I'm on vacation!\n"
    .string "My sis brought me along! Awesome!$"

CeladonCity_Hotel_Text_EggMoveTutorIntro::
    .string "I've devoted my life to studying the\n"
    .string "moves POKéMON pass down to their\p"
    .string "children.\n"
    .string "These moves are called EGG MOVES.\p"
    .string "Shall I teach one of your POKéMON?$"

CeladonCity_Hotel_Text_EggMoveTutorWhichMon::
    .string "Which POKéMON shall I teach\n"
    .string "an egg move?$"

CeladonCity_Hotel_Text_EggMoveTutorWhichMove::
    .string "Which egg move shall I teach?$"

CeladonCity_Hotel_Text_EggMoveTutorDone::
    .string "Wonderful! That move will serve\n"
    .string "it well!$"

CeladonCity_Hotel_Text_EggMoveTutorKnowsTMHM::
    .string "I'm sorry, but I can't teach this\n"
    .string "POKéMON.\p"
    .string "It knows TM and HM moves, and egg\n"
    .string "moves would only confuse it.$"

CeladonCity_Hotel_Text_EggMoveTutorAlreadyTaught::
    .string "This POKéMON has already learned an\n"
    .string "egg move from me.\p"
    .string "I can only teach one egg move to\n"
    .string "each POKéMON.$"

CeladonCity_Hotel_Text_EggMoveTutorNoEggMoves::
    .string "I'm sorry, but I have no egg moves\n"
    .string "I can teach that POKéMON.$"

CeladonCity_Hotel_Text_EggMoveTutorCantTeachEgg::
    .string "An egg? Even I can't teach an egg\n"
    .string "an egg move!$"

